meta_product_name: "Avant Garde"
meta_title: "Avant Garde - Invest in museum-worthy artworks"
meta_description: "New artwork campaigns go live on the Avant/Garde platform every month. Fractional ownership allows you to participate in the value increase of works by some of the best artists. Start with a small investment and grow your art collection over time."
meta_image: "meta-image.png" # should exist in `app/assets/images/`
twitter_account: "@avantgardeinve2"   # required for Twitter Cards
